### ISSUE TITLE
verifyBeforeRead could use some additional "Probably not what you want" verbage in CommsDSL_Specification, or maybe an implementation change?

### ISSUE THREAD

**Issue by dodohand** [arobenko/CommsDSL-Specification#2]
I ran into a situation where verifyBeforeRead="true" with first frame byte being the size field and last frame byte being a checksum led to the checksum being calculated over all received bytes, rather that all bytes of a frame excluding the checksum byte.
This may or may not be how you expect it to behave - it wasn't what I expected though, as it makes very little sense to me to calculate the checksum if you haven't read the size field. I can think of two possible improvements: 
1) try to read the size and then calculate checksum,
2) Add some verbage to the 'verifyBeforeRead' documentation along these lines:
  - verifyBeforeRead can be dangerous: verifyBeforeRead="true" causes a checksum calculation across all received bytes prior to evaluation of the 'size' layer. If you may receive multiple frames consecutively(, or partial frames ?), this can lead to frames being discarded.

**Comment by arobenko** [comment]
Yes, you are right, the documentation of the "verifyBeforeRead" property in the spec can be improved. I'll do it in the next release (should happen within a month or so).

In your specific case I assume that the checksum is calculated over the <size> layer as well. In such case the &lt;checksum&gt; is processed **before** the &lt;size&gt; (due to usage of verifyBeforeRead property of course), as the result the code just takes last available bytes in the buffer (rather than taking the value of &lt;size&gt; into account) and treats it as a checksum. But these are the implementation details of the generated code as well as COMMS library it uses.

Changing the code generator to analyze and warn about such case (using verifyBeforeRead property for the checksum that covers &lt;size&gt;) is NOT entirely correct. There are cases, especially when datagram (instead of stream) communication layer is used and the message is always received in full, so the checksum is always at the end of the buffer and usage of verifyBeforeRead property can be justified.
